require "aws-sdk"
require "securerandom"

fastlane_version "1.101.0"

default_platform :android

platform :android do
  def deploy
    extract_app_info
    fota_s3
  end

  desc "Deploy debug app to Shuttle"
  lane :deploy_debug do
    gradle(task: "assembleDebug")
    deploy
    shuttle
  end

  desc "Deploy STG app to Shuttle"
  lane :deploy_stg do
    gradle(task: "assembleStg")
    deploy
    shuttle
  end

  desc "Deploy release app to and Shuttle"
  lane :deploy_release do
    gradle(task: "assembleRelease")
    deploy
    shuttle
  end
end

